# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

gems :
  - jekyll-paginate

# Setup
title:            Thibaut Géry
tagline:          "Sharing things I've learned the hard way"
description:      "Sharing things I've learned the hard way"
url:              http://thibautgery.com

author:
  name:           'Thibaut Géry'
  url:            thibautgery.com

paginate:         5
