# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

gems :
  - jekyll-paginate
  - pygments

# Setup
title:            Thibaut Géry
tagline:          "Sharing things I've learned the hard way"
description:      "Sharing things I've learned the hard way"
host:             thibautgery.github.io
url:              http://thibautgery.com

author:
  name:           'Thibaut Géry'
  url:            thibautgery.com

paginate:         5
